<?php
declare(strict_types=1);

// CustomerioPipelines SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

CustomerioPipelinesUtility::setRegistrar(function (CustomerioPipelinesUtility $u): void {
    $u->clean = [CustomerioPipelinesClean::class, 'call'];
    $u->done = [CustomerioPipelinesDone::class, 'call'];
    $u->make_error = [CustomerioPipelinesMakeError::class, 'call'];
    $u->feature_add = [CustomerioPipelinesFeatureAdd::class, 'call'];
    $u->feature_hook = [CustomerioPipelinesFeatureHook::class, 'call'];
    $u->feature_init = [CustomerioPipelinesFeatureInit::class, 'call'];
    $u->fetcher = [CustomerioPipelinesFetcher::class, 'call'];
    $u->make_fetch_def = [CustomerioPipelinesMakeFetchDef::class, 'call'];
    $u->make_context = [CustomerioPipelinesMakeContext::class, 'call'];
    $u->make_options = [CustomerioPipelinesMakeOptions::class, 'call'];
    $u->make_request = [CustomerioPipelinesMakeRequest::class, 'call'];
    $u->make_response = [CustomerioPipelinesMakeResponse::class, 'call'];
    $u->make_result = [CustomerioPipelinesMakeResult::class, 'call'];
    $u->make_point = [CustomerioPipelinesMakePoint::class, 'call'];
    $u->make_spec = [CustomerioPipelinesMakeSpec::class, 'call'];
    $u->make_url = [CustomerioPipelinesMakeUrl::class, 'call'];
    $u->param = [CustomerioPipelinesParam::class, 'call'];
    $u->prepare_auth = [CustomerioPipelinesPrepareAuth::class, 'call'];
    $u->prepare_body = [CustomerioPipelinesPrepareBody::class, 'call'];
    $u->prepare_headers = [CustomerioPipelinesPrepareHeaders::class, 'call'];
    $u->prepare_method = [CustomerioPipelinesPrepareMethod::class, 'call'];
    $u->prepare_params = [CustomerioPipelinesPrepareParams::class, 'call'];
    $u->prepare_path = [CustomerioPipelinesPreparePath::class, 'call'];
    $u->prepare_query = [CustomerioPipelinesPrepareQuery::class, 'call'];
    $u->graphql_body = [CustomerioPipelinesGraphql::class, 'body'];
    $u->graphql_errors = [CustomerioPipelinesGraphql::class, 'errors'];
    $u->result_basic = [CustomerioPipelinesResultBasic::class, 'call'];
    $u->result_body = [CustomerioPipelinesResultBody::class, 'call'];
    $u->result_headers = [CustomerioPipelinesResultHeaders::class, 'call'];
    $u->transform_request = [CustomerioPipelinesTransformRequest::class, 'call'];
    $u->transform_response = [CustomerioPipelinesTransformResponse::class, 'call'];
});
